spring:
  application:
    name: ms-eventomax-productions
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:eventomax}
    password: ${RABBITMQ_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

eventomax:
  messaging:
    rabbitmq:
      exchange: cmd.direct
      routing-key:
        email: email.send
