spring.application.name=ms-eventomax-productions
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:eventomax_productions}
spring.datasource.username=${DB_USER:eventomax}
spring.datasource.password=${DB_PASSWORD:eventomax_dev}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
