spring:
  application:
    name: ms-eventomax-productions
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/eventomax_productions}
    username: ${DB_USER:eventomax}
    password: ${DB_PASSWORD:eventomax_dev}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
