spring:
  application:
    name: ms-eventomax-productions
  datasource:
    url: jdbc:postgresql://localhost:5432/eventomax_productions
    username: eventomax
    password: eventomax_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
